"use client";
import { FormEvent, useEffect, useState } from "react";
import { LoaderCircle, Star } from "lucide-react";
import { authenticatedFetch } from "@/lib/authenticated-fetch";
type Data = { settings: { enabled: boolean; price: number; durationDays: number }; products: Array<{ id: string; name: string }>; requests: Array<{ id: string; productName: string; amount: number; status: string }> };
export default function SupplierFeaturedListings() {
  const [data, setData] = useState<Data | null>(null); const [productId, setProductId] = useState(""); const [receipt, setReceipt] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { const response = await authenticatedFetch("/api/supplier/featured-listings"); const body = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(body.error); setData(body); }
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : "Listings could not be loaded.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await authenticatedFetch("/api/supplier/featured-listings", { method: "POST", body: JSON.stringify({ productId, mpesaReceipt: receipt }) }); const body = await response.json() as { error?: string }; setSaving(false); if (!response.ok) return setMessage(body.error || "Request could not be submitted."); setReceipt(""); setProductId(""); setMessage("Featured listing submitted for payment verification."); await load(); }
  if (!data) return <div className="card grid min-h-52 place-items-center"><LoaderCircle className="animate-spin" /></div>;
  return <div className="space-y-7"><header><p className="eyebrow">Paid visibility</p><h1 className="mt-2 font-display text-3xl font-bold">Featured listings</h1><p className="mt-2 text-sm text-ink/60">Promotions are clearly labelled and remain subject to stock availability.</p></header>{message && <p className="card p-3 text-sm">{message}</p>}<section className="card p-6"><div className="flex items-center gap-3"><Star className="text-marigold-dark" /><div><h2 className="font-display text-xl font-bold">Promote an assigned product</h2><p className="text-sm text-ink/55">{data.settings.enabled ? `KES ${data.settings.price.toLocaleString("en-KE")} for ${data.settings.durationDays} days` : "New requests are currently closed."}</p></div></div><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Product<select className="input-field mt-2" required value={productId} onChange={(e) => setProductId(e.target.value)}><option value="">Select product</option>{data.products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label className="text-sm font-semibold">M-Pesa receipt<input className="input-field mt-2 uppercase" required minLength={8} maxLength={20} value={receipt} onChange={(e) => setReceipt(e.target.value.toUpperCase())} /></label><button className="btn-primary sm:col-span-2" disabled={!data.settings.enabled || saving}>{saving ? "Submitting…" : "Submit paid listing"}</button></form></section><section className="card divide-y divide-line"><div className="p-5"><h2 className="font-display text-xl font-bold">Listing history</h2></div>{data.requests.length === 0 ? <p className="p-5 text-sm text-ink/55">No listing requests yet.</p> : data.requests.map((item) => <div key={item.id} className="flex justify-between gap-4 p-4 text-sm"><span className="font-semibold">{item.productName}</span><span className="capitalize text-ink/55">{item.status} · KES {item.amount.toLocaleString("en-KE")}</span></div>)}</section></div>;
}
