"use client";
import { useCallback, useEffect, useState } from "react";
import { Check, LoaderCircle, Save, X } from "lucide-react";
import { authenticatedFetch } from "@/lib/authenticated-fetch";
type Data = { settings: { enabled: boolean; price: number; durationDays: number }; requests: Array<{ id: string; supplierName: string; productName: string; mpesaReceipt: string; amount: number; status: string }>; summary: { pending: number; active: number; approvedRevenue: number } };
export default function FeaturedListingsAdmin() {
  const [data, setData] = useState<Data | null>(null); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await authenticatedFetch("/api/admin/featured-listings"); const body = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(body.error); setData(body); }, []);
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : "Could not load listings.")); }, [load]);
  async function save() { if (!data) return; setBusy("settings"); const response = await authenticatedFetch("/api/admin/featured-listings", { method: "PUT", body: JSON.stringify(data.settings) }); const body = await response.json() as { error?: string }; setBusy(""); if (!response.ok) return setMessage(body.error || "Settings could not be saved."); setMessage("Featured listing settings saved."); }
  async function review(id: string, decision: string) { if (decision === "approved" && !confirm("Confirm the M-Pesa receipt was verified before activating this paid placement.")) return; setBusy(id); const response = await authenticatedFetch("/api/admin/featured-listings", { method: "PATCH", body: JSON.stringify({ requestId: id, decision }) }); const body = await response.json() as { error?: string }; setBusy(""); if (!response.ok) return setMessage(body.error || "Request could not be reviewed."); await load(); }
  if (!data) return <div className="card grid min-h-52 place-items-center"><LoaderCircle className="animate-spin" /></div>;
  return <div className="space-y-7"><header><p className="eyebrow">Paid visibility</p><h1 className="mt-2 font-display text-3xl font-bold">Featured supplier listings</h1><p className="mt-2 text-sm text-ink/60">Configure transparent paid product placement and verify supplier payments.</p></header>{message && <p className="card p-3 text-sm">{message}</p>}<section className="card p-6"><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold">Fee (KES)<input className="input-field mt-2" type="number" min="0" value={data.settings.price} onChange={(e) => setData({ ...data, settings: { ...data.settings, price: Number(e.target.value) } })} /></label><label className="text-sm font-semibold">Duration (days)<input className="input-field mt-2" type="number" min="1" max="365" value={data.settings.durationDays} onChange={(e) => setData({ ...data, settings: { ...data.settings, durationDays: Number(e.target.value) } })} /></label><label className="flex items-center gap-3 self-end rounded-lg border border-line p-3"><input type="checkbox" checked={data.settings.enabled} onChange={(e) => setData({ ...data, settings: { ...data.settings, enabled: e.target.checked } })} /> Accept requests</label></div><button className="btn-primary mt-4 gap-2" onClick={() => void save()} disabled={busy === "settings"}><Save size={16} /> Save settings</button></section><section className="grid gap-4 sm:grid-cols-3">{[["Pending", data.summary.pending], ["Active", data.summary.active], ["Approved revenue", `KES ${data.summary.approvedRevenue.toLocaleString("en-KE")}`]].map(([label, value]) => <div className="card p-5" key={label}><p className="text-sm text-ink/55">{label}</p><p className="mt-2 font-display text-2xl font-bold">{value}</p></div>)}</section><section className="card divide-y divide-line">{data.requests.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 p-4"><div><p className="font-semibold">{item.productName} · {item.supplierName}</p><p className="text-xs text-ink/50">{item.mpesaReceipt} · KES {item.amount.toLocaleString("en-KE")} · {item.status}</p></div>{item.status === "pending" && <div className="flex gap-2"><button className="btn-primary px-3" disabled={busy === item.id} onClick={() => void review(item.id, "approved")}><Check size={16} /></button><button className="btn-secondary px-3 text-red-600" disabled={busy === item.id} onClick={() => void review(item.id, "rejected")}><X size={16} /></button></div>}</div>)}</section></div>;
}
